version: "3.8"

services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      # Mount current folder to container /app (matches WORKDIR)
      - .:/app
    # If you want read-only code, you can use :ro at the end
    # - .:/app:ro
